# Name of the domain bridge, used for node naming and logging
name: my_bridge
from_domain: 14
to_domain: 50
topics:
  # Bridge "/bot2/pose/global"
  sima_1/pose/global:
    type: geometry_msgs/msg/PoseWithCovarianceStamped
  
  # Bridge sima_1/pose/global to multiple domains
  sima_1/pose/global:
    type: geometry_msgs/msg/PoseWithCovarianceStamped
    to_domain: 51

  sima_1/pose/global:
    type: geometry_msgs/msg/PoseWithCovarianceStamped
    to_domain: 50

  sima_1/pose/global:
    type: geometry_msgs/msg/PoseWithCovarianceStamped
    to_domain: 53

  sima_1/pose/global:
    type: geometry_msgs/msg/PoseWithCovarianceStamped
    to_domain: 54  
  
  # Bridge sima_2/pose/global to multiple domains
  sima_2/pose/global:
    type: geometry_msgs/msg/PoseWithCovarianceStamped
    to_domain: 51

  sima_2/pose/global:
    type: geometry_msgs/msg/PoseWithCovarianceStamped
    to_domain: 50

  sima_2/pose/global:
    type: geometry_msgs/msg/PoseWithCovarianceStamped
    to_domain: 53

  sima_2/pose/global:
    type: geometry_msgs/msg/PoseWithCovarianceStamped
    to_domain: 54  
  
  # Bridge sima_3/pose/global to multiple domains
  sima_3/pose/global:
    type: geometry_msgs/msg/PoseWithCovarianceStamped
    to_domain: 51

  sima_3/pose/global:
    type: geometry_msgs/msg/PoseWithCovarianceStamped
    to_domain: 50

  sima_3/pose/global:
    type: geometry_msgs/msg/PoseWithCovarianceStamped
    to_domain: 53

  sima_3/pose/global:
    type: geometry_msgs/msg/PoseWithCovarianceStamped
    to_domain: 54  
  
  # Bridge sima_4/pose/global to multiple domains
  sima_4/pose/global:
    type: geometry_msgs/msg/PoseWithCovarianceStamped
    to_domain: 51

  sima_4/pose/global:
    type: geometry_msgs/msg/PoseWithCovarianceStamped
    to_domain: 50

  sima_4/pose/global:
    type: geometry_msgs/msg/PoseWithCovarianceStamped
    to_domain: 53

  sima_4/pose/global:
    type: geometry_msgs/msg/PoseWithCovarianceStamped
    to_domain: 54  
  
  # Bridge start signal topic to multiple domains
  robot/startup/sima/start:
    type: std_msgs/msg/Int16
    to_domain: 51
  
  robot/startup/sima/start:
    type: std_msgs/msg/Int16
    to_domain: 50
  
  robot/startup/sima/start:
    type: std_msgs/msg/Int16
    to_domain: 53
  
  robot/startup/sima/start:
    type: std_msgs/msg/Int16
    to_domain: 54

  # # Bridge "/clock" topic from doman ID 2 to domain ID 3
  # clock:
  #   type: rosgraph_msgs/msg/Clock
  # # Bridge "/chatter" topic from doman ID 2 to domain ID 3
  # chatter:
  #   type: example_interfaces/msg/String
  #   # Override QoS reliablity setting to be best effort
  #   # This affects the domain bridge subscription and publisher
  #   # This does NOT affect the other "chatter" bridge below, which is for a different domain
  #   qos:
  #     reliability: best_effort
  # # Also bridge "/chatter" topic from doman ID 2 to domain ID 4
  # chatter:
  #   type: example_interfaces/msg/String
  #   to_domain: 4
  # # Bridge reversed "/chatter" topic
  # chatter:
  #   type: example_interfaces/msg/String
  #   # Reverse 'from' and 'to' domains (bridge from domain ID 3 to domain ID 2)
  #   reversed: True
  # # Bridge bidirectional "/chatter" topic
  # chatter:
  #   type: example_interfaces/msg/String
  #   from_domain: 7
  #   to_domain: 8
  #   # Bridge from domain ID 7 to domain ID 8 AND from domain ID 8 to domain ID 7
  #   bidirectional: True

  # # Bridge "/chatter" topic from doman ID 2 to domain ID 3, but as "/chitter"
  # chatter:
  #   type: example_interfaces/msg/String
  #   remap: chitter